steps:
  - label: "🔐 Load secret & Bootstrap service account"
    key: "load-and-bootstrap"
    agents:
      queue: "kubernetes"
    command: |
      echo "==== STEP 1: Loading Kubeconfig Secret ===="
      export KUBECONFIG_SECRET="$(buildkite-agent secret get k8s_admin_kubeconfig)"
      if [ -z "$KUBECONFIG_SECRET" ]; then
        echo "❌ ERROR: Secret k8s_admin_kubeconfig not found in Buildkite Secrets!"
        echo "Please create this secret in your Buildkite Organization Settings → Secrets"
        exit 1
      fi
      echo "Secret loaded successfully (length: ${#KUBECONFIG_SECRET} chars)"
      echo "==== STEP 2: Creating Service Account ===="
    plugins:
      - Mykematt/k8s-bootstrap#v1.0.0:
          cluster-admin-kubeconfig: "${KUBECONFIG_SECRET}"
          namespace: "default"
          service-account-name: "deployer-service-account"
          permissions:
            - "deployments"
            - "pods"
            - "secrets"
            - "configmaps"
            - "services"

  - label: "🚀 Deploy nginx application"
    key: "deploy-nginx"
    depends_on: "load-and-bootstrap"
    agents:
      queue: "kubernetes"
    command: |
      echo "==== STEP 3: Deploying Application ===="
      echo "Downloading scoped kubeconfig artifact from Step 1..."
      buildkite-agent artifact download "kubeconfig-*" .
      export KUBECONFIG="$(find . -name 'kubeconfig-*')"
      echo "Using scoped kubeconfig: $KUBECONFIG"
      echo "Applying Kubernetes manifests with limited permissions..."
      kubectl apply -f k8s/configmap.yaml
      kubectl apply -f k8s/deployment.yaml
      kubectl apply -f k8s/service.yaml
      echo "✅ Deployment completed successfully!"