steps:
  - label: "ðŸ” Load kubeconfig secret"
    key: "load-secret"
    agents:
      queue: kubernetes
    command: |
      echo "Loading kubeconfig secret from Buildkite Secrets..."
      buildkite-agent secret get k8s_admin_kubeconfig > admin-kubeconfig.yaml
      echo "Secret loaded, file size: $(wc -c < admin-kubeconfig.yaml) bytes"
      buildkite-agent artifact upload admin-kubeconfig.yaml

  - label: "ðŸ› ï¸ Bootstrap service account" 
    key: "bootstrap-sa"
    depends_on: "load-secret"
    agents:
      queue: kubernetes
    plugins:
      - docker#v3.9.0:
          image: bitnami/kubectl:latest
          volumes:
            - ".:/workspace"
          workdir: /workspace
          environment:
            - BUILDKITE_PLUGIN_K8S_BOOTSTRAP_CLUSTER_ADMIN_KUBECONFIG
      - Mykematt/k8s-bootstrap#v1.0.0:
          namespace: "default"
          service-account-name: "deployer-service-account"
          permissions:
            - deployments
            - pods
            - secrets
            - configmaps
            - services
    command: |
      echo "Downloading admin kubeconfig..."
      buildkite-agent artifact download admin-kubeconfig.yaml .
      echo "Setting up environment for k8s-bootstrap plugin..."
      export BUILDKITE_PLUGIN_K8S_BOOTSTRAP_CLUSTER_ADMIN_KUBECONFIG="$(cat admin-kubeconfig.yaml)"
      echo "Environment variable length: $(echo "$BUILDKITE_PLUGIN_K8S_BOOTSTRAP_CLUSTER_ADMIN_KUBECONFIG" | wc -c) chars"

  - label: "ðŸš€ Deploy nginx application"
    key: "deploy-nginx"
    depends_on: "bootstrap-sa"
    agents:
      queue: "kubernetes"
    plugins:
      - docker#v3.9.0:
          image: bitnami/kubectl:latest
          volumes:
            - ".:/workspace"
          workdir: /workspace
    command: |
      echo "==== STEP 3: Deploying Application ===="
      echo "Downloading scoped kubeconfig artifact from Step 2..."
      buildkite-agent artifact download "kubeconfig-deployer-service-account.yaml" .
      
      # Set up kubeconfig
      mkdir -p ~/.kube
      cp kubeconfig-deployer-service-account.yaml ~/.kube/config
      
      echo "Using scoped kubeconfig for deployment..."
      echo "Applying Kubernetes manifests with limited permissions..."
      kubectl apply -f k8s/configmap.yaml
      kubectl apply -f k8s/deployment.yaml
      kubectl apply -f k8s/service.yaml
      echo "âœ… Deployment completed successfully!"