steps:
  - label: "🔐 Load secret & Bootstrap service account"
    key: "load-and-bootstrap"
    agents:
      queue: "kubernetes"
    plugins:
      - Mykematt/k8s-bootstrap#v1.0.0:
          namespace: "default"
          service-account-name: "deployer-service-account"
          cluster-admin-kubeconfig: $(buildkite-agent secret get k8s_admin_kubeconfig)
          permissions:
            - deployments
            - pods
            - secrets
            - configmaps
            - services

  - label: "🚀 Deploy nginx application"
    key: "deploy-nginx"
    depends_on: "load-and-bootstrap"
    agents:
      queue: "kubernetes"
    command: |
      echo "==== STEP 3: Deploying Application ===="
      echo "Downloading scoped kubeconfig artifact from Step 1..."
      buildkite-agent artifact download "kubeconfig-*" .
      export KUBECONFIG="$(find . -name 'kubeconfig-*')"
      echo "Using scoped kubeconfig: $KUBECONFIG"
      echo "Applying Kubernetes manifests with limited permissions..."
      kubectl apply -f k8s/configmap.yaml
      kubectl apply -f k8s/deployment.yaml
      kubectl apply -f k8s/service.yaml
      echo "✅ Deployment completed successfully!"